name: Production Release
description: Build and submit to App Store

environment:
  groups:
    - C11S_HOUSE_ENV
    - APP_STORE_CREDENTIALS

triggers:
  - name: Production Release
    description: Create production build for App Store
    events:
      - TAG
    tagChanges:
      - v*.*.*
    autoCancel: false
    isScheduledEnabled: false

actions:
  - name: validate_version
    actionType: SCRIPT
    scriptPath: ci_scripts/validate_version.sh
    isRequiredToPass: true

  - name: build
    actionType: BUILD
    destination: ANY_IOS_DEVICE
    scheme: C11SHouse
    platform: IOS
    configuration: Release
    isRequiredToPass: true

  - name: test
    actionType: TEST
    destination: ANY_IOS_SIMULATOR_DEVICE
    scheme: C11SHouse
    platform: IOS
    configuration: Release
    isRequiredToPass: true

  - name: ui_test
    actionType: TEST
    destination: ANY_IOS_SIMULATOR_DEVICE
    scheme: C11SHouseUITests
    platform: IOS
    isRequiredToPass: true

  - name: archive
    actionType: ARCHIVE
    scheme: C11SHouse
    platform: IOS
    configuration: Release
    artifactName: C11SHouse-Release-${CI_TAG}
    isRequiredToPass: true
    exportOptions:
      method: app-store
      teamID: ${TEAM_ID}
      uploadBitcode: true
      uploadSymbols: true
      generateAppStoreInformation: true

  - name: app_store_upload
    actionType: APP_STORE_UPLOAD
    appStoreConnectApiKeyId: ${APP_STORE_CONNECT_API_KEY_ID}
    releaseType: MANUAL
    isRequiredToPass: true